all: p10037

p10037:
	g++ -lm -O2 -std=c++11 -pipe -DONLINE_JUDGE -o 10037 10037.cpp
	./10037 < c1.in | diff c1.out -
	./10037 < c2.in | diff c2.out -
	./10037 < c3.in | diff c3.out -
	./10037 < c4.in | diff c4.out -
	./10037 < c5.in | diff c5.out -
	./10037 < c6.in | diff c6.out -
	./10037 < c7.in | diff c7.out -
	./10037 < c8.in | diff c8.out -
	./10037 < c9.in | diff c9.out -
	./10037 < c10.in | diff c10.out -

.PHONY: all p10315
